---
- hosts: splunkforwarders
  name: synchronize splunk
  become_method: sudo
  become_user: root
  become_flags: '-i'

  tasks:

  - name: deploy splunk apps
    copy:
      src: /opt/splunk/etc/deployment-apps
      dest: /var/tmp/splunktest
      owner: root
      group: root
    delegate_to: localhost
    become: true
    notify:
        - restart splunk

          #  - name: deploy splunk apps
          #    synchronize:
          #      mode: push
          #      src: /opt/splunk/etc/deployment-apps/
          #      #      dest: /opt/splunk/etc/apps/
          #      dest: /var/tmp/splunktest/
          #      perms: yes
          #      owner: yes
          #      group: yes
          #      ssh_args: "-l root"
          #    delegate_to: localhost
          #    notify:
          #        - restart splunk

  handlers:

  - name: restart splunk
    service: name=splunk state=restarted
    become: true

