---
- hosts: all
  name: synchronize splunk
  serial: 5
  become_method: sudo
  become_user: root
  become_flags: '-i'

  tasks:

  - name: deploy splunk apps
    synchronize:
      mode: push
      src: /opt/splunk/etc/deployment-apps/
      #      dest: /opt/splunk/etc/apps/
      dest: /var/tmp/splunktest/
      perms: yes
      owner: yes
      group: yes
      ssh_args: "-l root"
    delegate_to: localhost
    notify:
        - restart splunk

  handlers:

  - name: restart splunk
    service: name=splunk state=restarted
    become: true

